### ISSUE TITLE
dice term question

### ISSUE THREAD

**Issue by shinel94** [asgsaeid/ComboLoss#2]
in combo_loss.py, line 20,
code is combo = (ce_d_w * weighted_ce) - ((1 - ce_d_w) * (1 - d))
but last term also combo so i think that become plus or only d not 1-d
I hope to know about your opinion

**Comment by asgsaeid** [comment]
this was due to rewriting the function here; either (a - b) or a + (1-b) works; now code reflects the function in the paper
