### ISSUE TITLE
equation issue

### ISSUE THREAD

**Issue by talhaanwarch** [asgsaeid/ComboLoss#4]
According to paper equation 3, there should be   `-` instead of `*` 
![image](https://user-images.githubusercontent.com/37379131/126875472-5d045b74-e108-4e8e-b7ed-7735de6be56b.png)

but here it is `*`
out = - (ce_w * y_true_f `*`K.log(y_pred_f)) + ((1 - ce_w) * (1.0 - y_true_f) * K.log(1.0 - y_pred_f))

**Comment by eugene87222** [comment]
Same question. I think there are some typo on the paper. According to the definition of cross entropy, it must be `*` instead of `-`.

**Comment by asgsaeid** [comment]
modified the typo in the preprint, thank you.
